import { Theme } from "./colours.slint";
import "./fonts/xanh_mono/XanhMono-Regular.ttf";
import "./fonts/xanh_mono/XanhMono-Italic.ttf";
import "./fonts/roboto_mono/RobotoMono-Italic-VariableFont_wght.ttf";
import "./fonts/roboto_mono/RobotoMono-VariableFont_wght.ttf";
import { Player } from "./player.slint";
import { StatusBar } from "./status_bar.slint";
import { PlayerData } from "./player.slint";
export { PlayerData }
import { StatusBarData } from "./status_bar.slint";
export { StatusBarData }

export enum State {
    Player,
}

export component MainWindow inherits Window {
    width: 320px;
    height: 240px;
    title: "Vast";
    default-font-family: "Roboto Mono";
    background: Theme.background;

    property <State> displayed-screen: State.Player;
    in-out property <State> active-screen: State.Player;

    property <bool> fading: false;

    changed active-screen => {
        if (self.active-screen != self.displayed-screen) {
            self.fading = true;
        }
    }

    VerticalLayout {
        StatusBar {}

        Rectangle {
            background: Theme.background;
            width: root.width;
            height: root.height - 18px;

            player-layer := Player {
                width: root.width;
                height: parent.height;
                opacity: root.fading ? 0.0 : 1.0;
                visible: root.displayed-screen == State.Player;

                animate opacity {
                    duration: 150ms;
                    easing: ease-in-out;
                }
            }
        }
    }

    swap-timer := Timer {
        interval: 150ms;
        running: root.fading;
        triggered => {
            root.displayed-screen = root.active-screen;
            root.fading = false;
            self.running = false;
        }
    }
}