import { Theme } from "./colours.slint";
import "./fonts/xanh_mono/XanhMono-Regular.ttf";
import "./fonts/xanh_mono/XanhMono-Italic.ttf";
import "./fonts/roboto_mono/RobotoMono-Italic-VariableFont_wght.ttf";
import "./fonts/roboto_mono/RobotoMono-VariableFont_wght.ttf";

export component MainWindow inherits Window {
    width: 320px;
    height: 240px;
    title: "Vast";
    default-font-family: "Roboto Mono";
    background: Theme.background;

    in property <string> track-title: "No Track Loaded";
    in property <string> track-artist: "";
    in property <string> lyric-line: "";
    in property <bool> has-lyrics: false;
    in property <float> progress: 0.0;
    in property <string> time-label: "0:00 / 0:00";
    in property <bool> is-playing: false;

    // Track info
    VerticalLayout {
        padding: 14px;
        spacing: 10px;

        Text {
            text: root.track-title;
            font-size: 18px;
            font-weight: 700;
            color: white;
            horizontal-alignment: center;
            overflow: elide;
            font-family: "Xanh Mono";
        }
        Text {
            text: root.track-artist;
            font-size: 12px;
            color: #aaaaaa;
            horizontal-alignment: center;
            overflow: elide;
        }

        Text {
            text: root.has-lyrics ? root.lyric-line : "[no lyrics found]";
            font-size: 14px;
            color: root.has-lyrics ? Theme.text : #555555;
            horizontal-alignment: center;
            wrap: word-wrap;
            height: 40px;
        }
    }

    // Progress
    VerticalLayout {
        // Why does it do that? I don't know why it pushes it to the bottom, but that's
        // desired, so I guess that's good.
        Rectangle {}

        Text {
            text: root.time-label;
            font-size: 10px;
            color: Theme.text-2;
            horizontal-alignment: center;
        }

        Rectangle {
            height: 9px;
            background: Theme.background-2;
            Rectangle {
                x: 0px;
                y: 0px;
                width: parent.width * root.progress;
                height: parent.height;
                background: Theme.primary;
            }
        }
    }
}
