import "./fonts/roboto_mono/RobotoMono-VariableFont_wght.ttf";
import { Theme } from "./colours.slint";
import { WindowTile, WindowColors } from "./window.slint";
import { AppState, State } from "./state.slint";

export global SidebarEntryColors {
    in-out property <color> hover: #35293c;
    in-out property <color> hover-border: #3c2e44;

    in-out property <color> active: #ebd0ff;
}

export component SidebarEntry inherits Rectangle {
    in property <string> text;
    in-out property <bool> focused: false;
    callback activated();

    background: focused ? SidebarEntryColors.hover : transparent;

    width: 120px;
    height: 25px;

    border-radius: 7px;
    border-width: focused ? 2px : 0px;
    border-color: focused ? SidebarEntryColors.hover-border : transparent;

    animate background, border-color, border-width {
        duration: 200ms;
        easing: ease-out;
    }

    HorizontalLayout {
        padding: 5px;

        Text {
            color: root.focused ? SidebarEntryColors.active : Theme.text;
            animate color {
                duration: 100ms;
                easing: ease-out;
            }
            text: root.text;
            height: 15px;
            vertical-alignment: center;
            font-size: 13px;
            font-family: "Roboto Mono";
        }
    }
}

export component Menu inherits Rectangle {
    width: 140px;
    in-out property <bool> window-active: false;
    property <int> focused-index: 0;

    property <[string]> entries: ["Player", "Test"];

    callback entry-activated(int);
    entry-activated(index) => {
        if (index == 0) { AppState.state = State.Player; }
        if (index == 1) { debug("test"); }
    }

    public function navigate-down() {
        focused-index = Math.min(focused-index + 1, entries.length - 1);
    }
    public function navigate-up() {
        focused-index = Math.max(focused-index - 1, 0);
    }
    public function activate-selected() {
        root.entry-activated(focused-index);
    }

    HorizontalLayout {
        padding: 5px;
        spacing: 5px;
        // mimics WindowTile; "neccessary" (maybe? maybe not?) because the delay
        // in animation doesn't work (and probably the modified duration)
        Rectangle {
            VerticalLayout {
                padding: 5px;
                alignment: start;

                for entry[idx] in root.entries : SidebarEntry {
                    text: entry;
                    focused: root.focused-index == idx;
                    activated => { root.entry-activated(idx); }
                }
            }
            animate border-color { 
                delay: root.window-active ? 65ms : 0ms;
                duration: 750ms; 
                easing: cubic-bezier(0.23, 1.0, 0.32, 1.0); 
            }
    
            background: WindowColors.window-bg;
            border-width: 2px;
            border-radius: WindowColors.hypr-rounding;
            
            animate opacity {
                duration: 400ms;
                easing: ease-out;
            }

            opacity: root.window-active ? 1 : 0.6;
            border-color: root.window-active ? WindowColors.active-border : WindowColors.inactive-border;
        }
    }
}