import { Theme } from "./colours.slint";

component SquareImpulsinator inherits Rectangle {
    rect-for-background := Rectangle {
        width: 100%;
        height: 100%;
        background: Theme.text-2;

        property <bool> pulse-state: false;

        Timer {
            interval: 100ms;
            running: rect-for-background.pulse-state;
            triggered => {
                rect-for-background.pulse-state = false;
            }
        }

        states [
            opaque when pulse-state: {
                opacity: 1.0;
                in {
                    animate opacity { duration: 0ms; }
                }
            }
            transparent when !pulse-state: {
                opacity: 0;
                in {
                    animate opacity { duration: 800ms; easing: ease-out; }
                }
            }
        ]
    }

    public function pulse() {
        rect-for-background.pulse-state = true;
    }

    Path {
        width: 100%;
        height: 100%;
        fit: fill;
        stroke: Theme.text-2;
        stroke-width: 1px;
        commands: "M8 8 H92 V92 H8 Z M8 8 L92 92";
        opacity: 1;
    }
}

export component FourSquareMetronome inherits Rectangle {
    background: Theme.background;
    
    // Metronome State
    in-out property <int> current-beat: 0;
    
    // Automatic playback controls
    in property <bool> running: false;
    in property <duration> bpm-interval: 500ms; // 120 BPM default

    Timer {
        interval: root.bpm-interval;
        running: root.running;
        triggered => {
            root.tick();
        }
    }

    public function tick() {
        if (root.current-beat == 0) {
            one.pulse();
        } else if (root.current-beat == 1) {
            two.pulse();
        } else if (root.current-beat == 2) {
            three.pulse();
        } else if (root.current-beat == 3) {
            four.pulse();
        }
        
        root.current-beat += 1;
        if (root.current-beat >= 4) {
            root.current-beat = 0;
        }
    }

    public function reset() {
        root.current-beat = 0;
    }

    HorizontalLayout {
        spacing: 1px;

        one := SquareImpulsinator {
            width: self.height;
            height: root.height;
        }
        two := SquareImpulsinator {
            width: self.height;
            height: root.height;
        }
        three := SquareImpulsinator {
            width: self.height;
            height: root.height;
        }
        four := SquareImpulsinator {
            width: self.height;
            height: root.height;
        }
    }
}