import { Theme } from "./colours.slint";
import "./fonts/xanh_mono/XanhMono-Regular.ttf";
import "./fonts/xanh_mono/XanhMono-Italic.ttf";
import "./fonts/roboto_mono/RobotoMono-Italic-VariableFont_wght.ttf";
import "./fonts/roboto_mono/RobotoMono-VariableFont_wght.ttf";
import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import { MarqueeText } from "./marquee.slint";

export global PlayerData {
    in-out property <string> track-title: "No Track Loaded";
    in-out property <string> track-artist: "Vast...";
    in-out property <string> lyric-line: "";
    in-out property <bool> has-lyrics: false;
    in-out property <float> progress: 0.0;
    in-out property <string> time-label: "--:-- / --:--";
    in-out property <bool> is-playing: false;
    in-out property <string> extra-info: "";
}

export component LyricCrossfade {
    property <string> current-lyric: PlayerData.lyric-line;

    property <string> displayed-text: "";
    property <string> incoming-text: "";
    property <bool> animating: false;

    init => {
        displayed-text = current-lyric;
    }

    changed current-lyric => {
        if (current-lyric != displayed-text && current-lyric != incoming-text) {
            incoming-text = current-lyric;
            animating = true;
            swap-timer.running = true;
        }
    }

    swap-timer := Timer {
        interval: 320ms;
        running: false;
        triggered => {
            displayed-text = incoming-text;
            animating = false;
            self.running = false;
        }
    }

    height: 40px;

    Text {
        text: displayed-text;
        font-size: 14px;
        color: PlayerData.has-lyrics ? Theme.text : #555555;
        horizontal-alignment: center;
        wrap: word-wrap;
        width: 100%;
        
        y: 0px;
        opacity: 1;

        states [
            active when animating: {
                y: 20px;
                opacity: 0;
                in { 
                    animate y { duration: 500ms; easing: ease-out-quart; }
                    animate opacity { duration: 500ms;  easing: ease-out-quart; }
                }
            }
        ]
    }

    // Incoming!!
    Text {
        text: incoming-text;
        font-size: 14px;
        color: PlayerData.has-lyrics ? Theme.text : #555555;
        horizontal-alignment: center;
        wrap: word-wrap;
        width: 100%;
        
        y: -20px;
        opacity: 0;

        states [
            active when animating: {
                y: 0px;
                opacity: 1;
                in { 
                    animate y { duration: 500ms; easing: ease-out-quart; }
                    animate opacity { duration: 500ms;  easing: ease-out-quart; }
                }
            }
        ]
    }
}

export component Player inherits Rectangle {
    width: 320px;
    height: 240px;
    background: Theme.background;

    // Track info
    VerticalLayout {
        padding: 14px;
        spacing: 10px;

        VerticalLayout {
            MarqueeText {
                text: PlayerData.track-title;
                font-size: 18px;
                font-weight: 700;
                font-family: "Xanh Mono";
                width: parent.width;
                speed: PlayerData.is-playing ? 60 : 25;
                animate speed {
                    duration: 1200ms;
                    easing: ease-out;
                }
            }
            Text {
                text: PlayerData.track-artist;
                font-size: 12px;
                color: #aaaaaa;
                horizontal-alignment: left;
                overflow: elide;
            }

            Rectangle {}
        }

        LyricCrossfade {
            height: 40px;
        }
    }

    // Progress
    VerticalLayout {
        Rectangle {}

        HorizontalLayout {
            padding-left: 4px;
            padding-right: 4px;
            Text {
                text: PlayerData.time-label;
                font-size: 10px;
                color: Theme.text-2;
                horizontal-alignment: left;
                height: 16px;
            }

            Image {
                source: PlayerData.is-playing ? @image-url("assets/pause.svg") : @image-url("assets/play.svg");
                width: 10px;
                height: 10px;
                colorize: Theme.text-2; 
                vertical-alignment: center;
            }
        }

        Rectangle {
            height: 9px;
            background: Theme.background-2;
            Rectangle {
                x: 0px;
                y: 0px;
                width: parent.width * PlayerData.progress;
                height: parent.height;
                background: Theme.primary;
            }
        }
    }
}
