import { Theme } from "./colours.slint";
import { MarqueeText } from "./marquee.slint";
import "./fonts/xanh_mono/XanhMono-Regular.ttf";
import "./fonts/xanh_mono/XanhMono-Italic.ttf";
import "./fonts/roboto_mono/RobotoMono-Italic-VariableFont_wght.ttf";
import "./fonts/roboto_mono/RobotoMono-VariableFont_wght.ttf";
import { PlayerData } from "player.slint";

export global StatusBarData {
    in-out property <int> battery: 0;
    in-out property <bool> has_battery: false;
    in-out property <bool> is_charging: false;

    in-out property <string> time: "00:00 XX";
    in-out property <bool> has_time: false;

    in-out property <bool> show_status_bar_lyrics: false;
}

export component StatusBarLyricsAndWhatever {
    property <string> current-lyric: PlayerData.lyric-line;

    property <string> displayed-text: "";
    property <string> pending-text: "";
    property <bool> fading-out: false;
    property <bool> show_lyrics: StatusBarData.show_status_bar_lyrics;

    init => {
        displayed-text = current-lyric;
    }

    changed current-lyric => {
        pending-text = current-lyric;
        fading-out = true;
        swap-timer.running = true;
    }

    changed show_lyrics => {
        root.opacity = root.show_lyrics ? 1 : 0
    }

    swap-timer := Timer {
        interval: 200ms;
        running: false;
        triggered => {
            displayed-text = pending-text;
            
            fading-out = false;
            self.running = false;
        }
    }

    height: 40px;

    Text {
        text: displayed-text;
        font-size: 10px;
        color: Theme.text-2;
        horizontal-alignment: center;
        overflow: elide;
        width: 100%;

        opacity: fading-out ? 0 : 1;
        animate opacity { duration: 150ms; easing: ease-out; }
    }

    animate opacity { duration: 150ms; easing: ease-out; }
}

export component StatusBar inherits Rectangle {
    width: 320px;
    height: 18px;
    background: Theme.background;
    border-color: #504653;
    border-width: 1px;

    HorizontalLayout {
        padding-left: 4px;
        padding-right: 4px;
        alignment: space-between;

        if StatusBarData.has_battery : HorizontalLayout {
            visible: StatusBarData.has_battery;
            
            if !StatusBarData.is_charging : Image {
                source: StatusBarData.battery >= 0 && StatusBarData.battery <= 25 ? @image-url("assets/battery/25.svg") :
                        StatusBarData.battery >= 26 && StatusBarData.battery <= 50 ? @image-url("assets/battery/50.svg") :
                        StatusBarData.battery >= 51 && StatusBarData.battery <= 75 ? @image-url("assets/battery/75.svg") :
                        StatusBarData.battery >= 76 && StatusBarData.battery <= 100 ? @image-url("assets/battery/100.svg") : 
                        @image-url("assets/question.svg");

                width: 21px;
                height: 11px;
                colorize: Theme.text-2; 
                vertical-alignment: center;
                y: 3.5px;
            }
            if StatusBarData.is_charging : Image {
                source: @image-url("assets/battery/charging.svg");
                width: 21px;
                height: 11px;
                colorize: Theme.text-2; 
                vertical-alignment: center;
                y: 3.5px;
            }

            Rectangle {
                width: 4px;
            }

            Text {
                text: StatusBarData.battery + "%";
                font-size: 10px;
                color: Theme.text-2;
                vertical-alignment: center;
                font-family: "Roboto Mono";
            }
        }
        if !StatusBarData.has_battery : Rectangle {}

        Text {
            visible: StatusBarData.has_time;
            text: StatusBarData.time;
            font-family: "Roboto Mono";
            font-size: 10px;
            font-weight: 400;
            color: Theme.text-2;
            height: 15px;
            vertical-alignment: center;
        }
    }

    StatusBarLyricsAndWhatever {
        height: 15px;
        width: 200px;
    }

    /*
    MarqueeText {
        text: PlayerData.lyric-line;
        height: 15px;
        width: 200px;
        text-color: Theme.text-2;
        font-family: "Roboto Mono";
        font-size: 10px;
        font-weight: 400;
        speed: 40;
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
    }
    */
}