import { Theme } from "./colours.slint";

export global WindowColors {
    in-out property <color> active-border: #ae84cf;
    in-out property <color> inactive-border: #2c2d38af;

    in-out property <length> hypr-rounding: 10px;
    in-out property <length> hypr-gaps: 10px;

    in-out property <color> window-bg: #201a22;
    in-out property <color> window-text: #cdd6f4;
    in-out property <color> window-accent: #ae84cf;
}

export component Window inherits Rectangle {
    in property <bool> active: false;
    
    background: WindowColors.window-bg;
    border-width: 2px;
    border-radius: WindowColors.hypr-rounding;
    
    animate border-color { 
        duration: 400ms; 
        easing: cubic-bezier(0.23, 1.0, 0.32, 1.0); 
    }
    
    animate opacity {
        duration: 400ms;
        easing: ease-out;
    }

    // Are we going to keep this?
    border-color: ta.has-hover || active ? WindowColors.active-border : WindowColors.inactive-border;
    ta := TouchArea {
        width: 100%;
        height: 100%;
    }
}