import { Theme } from "./colours.slint";

component ReactiveSquareImpulsinator inherits Rectangle {
    rect-for-background := Rectangle {
        width: 100%;
        height: 100%;
        background: Theme.text-2;

        property <bool> pulse-state: false;

        Timer {
            interval: 100ms;
            running: rect-for-background.pulse-state;
            triggered => {
                rect-for-background.pulse-state = false;
            }
        }

        states [
            opaque when pulse-state: {
                opacity: 1.0;
                in {
                    animate opacity { duration: 0ms; }
                }
            }
            transparent when !pulse-state: {
                opacity: 0;
                in {
                    animate opacity { duration: 1000ms; easing: ease-out; }
                }
            }
        ]
    }

    in property <int> current-beat;
    in property <int> when-do-i-go;

    changed current-beat => {
        if current-beat == when-do-i-go {
            rect-for-background.pulse-state = true;
        }
    }

    Path {
        width: 100%;
        height: 100%;
        fit: fill;
        stroke: Theme.text-2;
        stroke-width: 1px;
        commands: "M8 8 H92 V92 H8 Z M8 8 L92 92";
        opacity: 1;
    }
}

export component SquareMetronome {    
    in-out property <int> current-beat: 0;
    in-out property <int> beats-per-measure: 4;

    HorizontalLayout {
        spacing: 1px;

        for n in root.beats-per-measure : ReactiveSquareImpulsinator {
            width: self.height;
            height: root.height;
            current-beat: root.current-beat;
            when-do-i-go: n;
        }
    }
}